### ISSUE TITLE
How to obtain the trajectory image

### ISSUE THREAD

**Issue by xhangHU** [TRI-ML/KP3D#9]
How to obtain the trajectory image，thanks！

**Comment by RaresAmbrus** [comment]
Hi, when running the evaluation script, the trajectory image should be saved in the output folder you specified.

**Comment by xhangHU** [comment]
Computing scale alignment.
Traceback (most recent call last):
  File "kp3d/evaluation/evaluate_keypoint_odometry.py", line 316, in <module>
    main()
  File "kp3d/evaluation/evaluate_keypoint_odometry.py", line 294, in main
    stderr=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './kp3d/externals/cpp/evaluate_odometry': './kp3d/externals/cpp/evaluate_odometry'

When I ran kitti evaluation directly, I encountered this. It seems that the file type name (.cpp) is missing. I tried to match the name but it still doesn’t work.
